services:
  - type: web
    name: getza-backend-new
    env: node
    region: oregon
    plan: free
    autoDeploy: "yes"
    buildCommand: echo "Built"
    startCommand: node --version
    healthCheckPath: /api/health
