services:
  - type: web
    name: getza-backend
    env: node
    region: oregon
    plan: free
    autoDeploy: "no"
    buildCommand: echo "Built" && npm install
    startCommand: node -e "console.log('Started'); setInterval(()=>{}, 100)"
