services:
  - type: web
    name: getza-backend
    env: node
    region: oregon
    plan: free
    autoDeploy: "no"
    buildCommand: echo "Built"
    startCommand: node -e "setInterval(()=>{}, 100000)"
